version: 2

jobs:
  build:
    working_directory: ~/matminer
    docker:
      - image: circleci/python:3.6.2
    steps:
      - checkout
      - run:
          name: Make tox env
          command: |
            mkdir ~/tox_env
            python -m venv ~/tox_env
            source ~/tox_env/bin/activate
            pip install tox tox-pyenv
            cd ~
            git clone https://github.com/txie-93/cgcnn.git
            echo 'export PYTHONPATH="$PYTHONPATH:$HOME/cgcnn"' >> $BASH_ENV
      - run:
          name: Run matminer tests
          command: |
            source ~/tox_env/bin/activate
            tox