version: 2

jobs:
  build:
    working_directory: ~/matminer
    docker:
      - image: circleci/python:3.6.2
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            sudo pip install tox tox-pyenv
      - run:
          name: Test with tox
          command: tox