version: 2

jobs:
  build:
    working_directory: ~/matminer
    docker:
      - image: circleci/python:3.6.2
    steps:
      - checkout
      - run:
          name: make tox env and run tests
          command: |
            mkdir ~/tox_env
            python -m venv ~/tox_env
            source ~/tox_env/bin/activate
            pip install --user tox tox-pyenv
      - run:
          name: run tests
          command: tox