version: 2

jobs:
  build:
    working_directory: ~/matminer
    docker:
      - image: circleci/python:3.6.2
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Make tox env
          command: |
            mkdir ~/tox_env
            python -m venv ~/tox_env
            source ~/tox_env/bin/activate
            pip install --upgrade pip
            pip install --upgrade setuptools
            pip install tox tox-pyenv
      - run:
          name: Run matminer tests
          command: |
            source ~/tox_env/bin/activate
            tox
      - save_cache:
          paths:
          - ./test_env
          key: v1-dependencies-{{ checksum "requirements.txt" }}