name: Full test


# Run this workflow only on release
on:
  - release
#    types: [published, created, released]
  - workflow_dispatch
#    inputs:
#      name:
#        description: 'Person to greet'
#        required: true
#        default: 'Mona the Octocat'
#  - release
#  - schedule
#    - cron
#  - schedule:
#    cron: '0 12 1 * *'

jobs:

  test:
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8]

    runs-on: ubuntu-latest

    env:
      PMG_MAPI_KEY: ${{ secrets.PMG_MAPI_KEY }}
      MPDS_KEY: ${{ secrets.MPDS_KEY }}
      CITRINATION_API_KEY: ${{ secrets.CITRINATION_API_KEY }}
      RUNNING_ON_GHACTIONS: "True"
      MATMINER_DATASET_FULL_TEST: True
      MPLBACKEND: "Agg"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run full tests including dataset downloads
      run: |
        python3 -m venv test_env
        . test_env/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements-optional.txt -r requirements-dev.txt
        pip install -e .
        pytest --cov=matminer matminer
