name: Linting

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python${{ matrix.python-version }} -m pip install --upgrade pip pip-tools
          python${{ matrix.python-version }} -m piptools sync --user requirements/ubuntu-latest_py${{ matrix.python-version }}_extras.txt

#      - name: mypy
#        run: |
#          mypy --version
#          rm -rf .mypy_cache
#          mypy matminer
#      - name: pydocstyle
#        run: |
#          pydocstyle --count matminer
#      - name: pylint
#        run: |
#          pylint matminer
      - name: black
        run: |
          black --version
          black --check --diff --color matminer
      - name: flake8
        run: |
          flake8 --version
          flake8 --count --show-source --statistics matminer
          # exit-zero treats all errors as warnings.
          flake8 --count --exit-zero --max-complexity=20 --statistics matminer
