# This workflow runs only on Ubuntu and aims to be more complete than the Mac and Windows workflows.
# In particular, Openbabel and many of the external command line dependencies are included for testing.defaults:
# The ext package is also only tested in this workflow. Coverage is also computed based on this platform.
name: Testing

on: [ push, pull_request ]

jobs:

  test:
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.8", "3.9"]
        mongodb-version: ['4.0']

    runs-on: ubuntu-latest

    env:
      PMG_MAPI_KEY: ${{ secrets.PMG_MAPI_KEY }}
      MPDS_KEY: ${{ secrets.MPDS_KEY }}
      CITRINATION_API_KEY: ${{ secrets.CITRINATION_API_KEY }}
      MATMINER_DATASET_FULL_TEST: False
      RUNNING_ON_GHACTIONS: "True"
      MPLBACKEND: "Agg"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"
        cache-dependency-path: '**/setup.py'

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.6.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - name: Install Python dependencies
      run: |
        python${{ matrix.python-version }} -m pip install --upgrade pip pip-tools
        python${{ matrix.python-version }} -m piptools sync --user requirements/ubuntu-latest_py${{ matrix.python-version }}_extras.txt
        # Using non-editable install for testing building of MANIFEST files
        python${{ matrix.python-version }} -m pip install --no-deps .

    - name: Run tests
      run: |
        # Sleeping to allow mongo a bit more time to boot, avoiding connect errors
        sleep 10
        echo "start mongo ..."
        mongo localhost/admin --eval 'db.createUser({user: "admin",pwd: "password",roles: [ { role: "root", db: "admin" } ]})'
        echo "run tests ..."
        python${{ matrix.python-version }} -m pytest --cov=matminer matminer
