# This workflow runs only on Ubuntu and aims to be more complete than the Mac and Windows workflows.
# In particular, Openbabel and many of the external command line dependencies are included for testing.defaults:
# The ext package is also only tested in this workflow. Coverage is also computed based on this platform.
name: Testing

on: [ push, pull_request ]

jobs:

  test:
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8]

    runs-on: ubuntu-latest

    env:
      MATMINER_DATASET_FULL_TEST: True

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements-optional.txt -r requirements-dev.txt
        pip install -e .
    - name: Run tests
      run: |
        python setup.py test
